# Generated by Django 3.2.3 on 2021-06-03 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSchemaBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(default='', max_length=20, null=True)),
                ('column_separator', models.CharField(choices=[(',', 'Comma(,)'), ('|', 'Forward slash (|)'), (';', 'Semicolon(;)')], default=';', max_length=15)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')"), ("'''", "Triple-quote(''')"), ('"""', 'Triple-quote(""")'), ('()', 'Bracket(())'), ('[]', 'Straight Brackets([])')], default="'", max_length=15)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Структура файла',
                'verbose_name_plural': 'Структура файлы',
                'db_table': 'mdl_schema_basic_info',
            },
        ),
        migrations.CreateModel(
            name='TblSchemaColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(default='', max_length=20, null=True)),
                ('column_type', models.CharField(choices=[('full_name', 'Full Name'), ('company', 'Company'), ('address', 'Address'), ('job', 'Job'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('int', 'Integer'), ('date', 'Date')], default='full_name', max_length=10)),
                ('int_from', models.PositiveIntegerField(default=0, null=True)),
                ('int_to', models.PositiveIntegerField(default=0, null=True)),
                ('sentences_number', models.PositiveIntegerField(default=0, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator_service.tblschemabasicinfo')),
            ],
            options={
                'verbose_name': 'Структура столбцы',
                'verbose_name_plural': 'Структура столбцы',
                'db_table': 'mdl_schema_columns',
            },
        ),
        migrations.CreateModel(
            name='TblDataSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'ready'), ('process', 'processing')], default='process', max_length=11)),
                ('csv_file', models.CharField(default='', max_length=300, null=True)),
                ('rows_number', models.PositiveIntegerField(default=0, null=True)),
                ('task_id', models.CharField(default='', max_length=300, null=True)),
                ('task_status', models.CharField(default='', max_length=40, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator_service.tblschemabasicinfo')),
            ],
            options={
                'verbose_name': 'Набор данных',
                'verbose_name_plural': 'Наборы данных',
                'db_table': 'mdl_datasets',
            },
        ),
    ]
