# Generated by Django 3.2.3 on 2021-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblSchemaColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(default='', max_length=20, null=True)),
                ('column_type', models.CharField(choices=[('full_name', 'full_name'), ('age', 'age'), ('company', 'company')], default='full_name', max_length=9)),
                ('int_from', models.PositiveIntegerField(default=0, null=True)),
                ('int_to', models.PositiveIntegerField(default=0, null=True)),
                ('order', models.PositiveIntegerField(default=0, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Структура столбцы',
                'verbose_name_plural': 'Структура столбцы',
                'db_table': 'mdl_schema_columns',
            },
        ),
        migrations.CreateModel(
            name='TblSchemaBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=20, null=True)),
                ('column_separator', models.CharField(default=',', max_length=1, null=True)),
                ('string_character', models.CharField(default='"', max_length=1, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('columns', models.ManyToManyField(to='generator_service.TblSchemaColumns')),
            ],
            options={
                'verbose_name': 'Структура файла',
                'verbose_name_plural': 'Структура файлы',
                'db_table': 'mdl_schema_basic_info',
            },
        ),
    ]
