# Generated by Django 3.2.3 on 2021-05-29 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblschemabasicinfo',
            old_name='file_name',
            new_name='schema_name',
        ),
        migrations.AlterField(
            model_name='tblschemacolumns',
            name='column_type',
            field=models.CharField(choices=[('full_name', 'full_name'), ('age', 'age'), ('company', 'company')], default='full_name', max_length=10),
        ),
        migrations.CreateModel(
            name='TblDataSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('full_name', 'full_name'), ('age', 'age'), ('company', 'company')], default='processing', max_length=11)),
                ('csv_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator_service.tblschemabasicinfo')),
            ],
            options={
                'verbose_name': 'Набор данных',
                'verbose_name_plural': 'Наборы данных',
                'db_table': 'mdl_datasets',
            },
        ),
    ]
