# Generated by Django 3.2.3 on 2021-06-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemabasicinfo',
            name='schema_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
