# Generated by Django 3.2.3 on 2021-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0003_alter_tbldatasets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatasets',
            name='status',
            field=models.CharField(choices=[(1, 'ready'), (2, 'processing')], default=2, max_length=11),
        ),
    ]
