# Generated by Django 3.2.3 on 2021-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0004_alter_tbldatasets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemabasicinfo',
            name='columns',
            field=models.ManyToManyField(related_name='schema_basic_info', to='generator_service.TblSchemaColumns'),
        ),
    ]
