# Generated by Django 3.2.3 on 2021-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0005_alter_tblschemabasicinfo_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemacolumns',
            name='column_type',
            field=models.CharField(choices=[('full_name', 'Full Name'), ('age', 'Age'), ('company', 'Company'), ('address', 'Address'), ('job', 'Job'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('int', 'Integer'), ('date', 'Date')], default='full_name', max_length=10),
        ),
    ]
