# Generated by Django 3.2.3 on 2021-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0006_alter_tblschemacolumns_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblschemacolumns',
            name='sentences_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
