# Generated by Django 3.2.3 on 2021-05-29 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator_service', '0008_alter_tblschemacolumns_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblschemabasicinfo',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
