# Generated by Django 3.2.3 on 2021-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0009_tblschemabasicinfo_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemabasicinfo',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma(,)'), ('|', 'Forward slash (|)'), (';', 'Semicolon(;)')], default=';', max_length=15),
        ),
        migrations.AlterField(
            model_name='tblschemabasicinfo',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], default="'", max_length=15),
        ),
    ]
