# Generated by Django 3.2.3 on 2021-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0010_auto_20210529_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemabasicinfo',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')"), ("'''", "Triple-quote(')")], default="'", max_length=15),
        ),
    ]
