# Generated by Django 3.2.3 on 2021-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0011_alter_tblschemabasicinfo_string_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemabasicinfo',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')"), ("'''", "Triple-quote(''')"), ('"""', 'Triple-quote(""")'), ('()', 'Bracket(())')], default="'", max_length=15),
        ),
    ]
