# Generated by Django 3.2.3 on 2021-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0013_alter_tblschemabasicinfo_string_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblschemabasicinfo',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
