# Generated by Django 3.2.3 on 2021-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0014_tblschemabasicinfo_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatasets',
            name='rows_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
