# Generated by Django 3.2.3 on 2021-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0015_tbldatasets_rows_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatasets',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('process', 'processing')], default='process', max_length=11),
        ),
    ]
