# Generated by Django 3.2.3 on 2021-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0016_alter_tbldatasets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatasets',
            name='csv_file',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
