# Generated by Django 3.2.3 on 2021-06-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0017_alter_tbldatasets_csv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblschemabasicinfo',
            name='columns',
        ),
        migrations.AddField(
            model_name='tblschemacolumns',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator_service.tblschemabasicinfo'),
        ),
    ]
