# Generated by Django 3.2.3 on 2021-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0018_auto_20210601_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschemacolumns',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
