# Generated by Django 3.2.3 on 2021-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0019_alter_tblschemacolumns_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatasets',
            name='task_id',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
