# Generated by Django 3.2.3 on 2021-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_service', '0020_tbldatasets_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatasets',
            name='task_status',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
